# Generated by Django 5.1.1 on 2024-10-23 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makoapp', '0003_remove_role_description_remove_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_username',
        ),
    ]
