# Generated by Django 5.1.1 on 2024-10-23 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makoapp', '0004_remove_user_user_password_remove_user_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='makoapp.role'),
        ),
    ]
