# Generated by Django 5.1.2 on 2024-11-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makoapp', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
