# Generated by Django 5.1.2 on 2024-11-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makoapp', '0007_property_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='documentation_file',
            field=models.FileField(blank=True, null=True, upload_to='documentation_files/'),
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
