# Generated by Django 5.1.2 on 2024-11-04 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makoapp', '0009_document_documentation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='documentation_file',
        ),
        migrations.AlterField(
            model_name='document',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makoapp.property'),
        ),
    ]
