# Generated by Django 5.1.2 on 2024-11-04 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makoapp', '0010_remove_document_documentation_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties_bought', to=settings.AUTH_USER_MODEL),
        ),
    ]
