# Generated by Django 5.1.1 on 2024-12-04 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makoapp', '0012_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_bought', to=settings.AUTH_USER_MODEL),
        ),
    ]
